apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: data-influx-claim
  name: data-influx-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi